version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 1
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      npm:
        patterns:
          - "*"
    open-pull-requests-limit: 1
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    groups:
      cargo:
        patterns:
          - "*"
    open-pull-requests-limit: 1